export type colorType =
    "primary" |
    "onPrimary" |
    "primaryContainer" |
    "onPrimaryContainer" |
    "primaryVariant" |
    "onPrimaryVariant" |
    "secondary" |
    "onSecondary" |
    "secondaryContainer" |
    "onSecondaryContainer" |
    "secondaryVariant" |
    "onSecondaryVariant" |
    "tertiary" |
    "onTertiary" |
    "tertiaryContainer" |
    "onTertiaryContainer" |
    "tertiaryVariant" |
    "onTertiaryVariant" |
    "info" |
    "onInfo" |
    "infoContainer" |
    "onInfoContainer" |
    "warn" |
    "onWarn" |
    "WarnContainer" |
    "onWarmContainer" |
    "error" |
    "onError" |
    "errorContainer" |
    "onErrorContainer" |
    "surface" |
    "onSurface" |
    "surfaceVariant" |
    "onSurfaceVariant" |
    "outline" |
    "primary-0" |
    "primary-1" |
    "primary-2" |
    "primary-3" |
    "primary-4" |
    "primary-5" |
    "primary-6" |
    "primary-7" |
    "primary-8" |
    "primary-9" |
    "secondary-0" |
    "secondary-1" |
    "secondary-2" |
    "secondary-3" |
    "secondary-4" |
    "secondary-5" |
    "secondary-6" |
    "secondary-7" |
    "secondary-8" |
    "secondary-9" |
    "tertiary-0" |
    "tertiary-1" |
    "tertiary-2" |
    "tertiary-3" |
    "tertiary-4" |
    "tertiary-5" |
    "tertiary-6" |
    "tertiary-7" |
    "tertiary-8" |
    "tertiary-9" |
    "info-0" |
    "info-1" |
    "info-2" |
    "info-3" |
    "info-4" |
    "info-5" |
    "info-6" |
    "info-7" |
    "info-8" |
    "info-9" |
    "warn-0" |
    "warn-1" |
    "warn-2" |
    "warn-3" |
    "warn-4" |
    "warn-5" |
    "warn-6" |
    "warn-7" |
    "warn-8" |
    "warn-9" |
    "error-0" |
    "error-1" |
    "error-2" |
    "error-3" |
    "error-4" |
    "error-5" |
    "error-6" |
    "error-7" |
    "error-8" |
    "error-9" |
    "surface-0" |
    "surface-1" |
    "surface-2" |
    "surface-3" |
    "surface-4" |
    "surface-5" |
    "surface-6" |
    "surface-7" |
    "surface-8" |
    "surface-9" |
    "outline-0" |
    "outline-1" |
    "outline-2" |
    "outline-3" |
    "outline-4" |
    "outline-5" |
    "outline-6" |
    "outline-7" |
    "outline-8" |
    "outline-9";